language: minimal
services:
- docker
addons:
  ssh_known_hosts: 192.46.234.106
before_script: export DOCKER_TAG=$(git log -1 --pretty=format:%h)
script: docker build -t "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$DOCKER_TAG" -t "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest" node
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in node/ci/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: bash node/ci/deploy.sh
  on:
    branch: master